// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "0d9238d9-4562-44be-8998-494fce39e68b");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1573212520);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1573212640);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1573212040);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1573212280);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1573212160);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1573212400);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1572076861);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1572076741);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 69986);
user_pref("browser.cache.disk.capacity", 747520);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 5);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1572101076);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{cec7f12e-4ec8-4aab-be94-dd4f076a0ae7}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1573212069141");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1573213839141");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1573212072689");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1573215672689");
user_pref("browser.search.region", "ID");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190718161435");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1573212030");
user_pref("browser.slowStartup.averageTime", 19282);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1573212017);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1572101087922");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "eccbd8e4f42b4086a5847f65b2535c2e");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 06 Nov 2019 18:02:02 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1573212521);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190718161435");
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{6a19cc46-cad3-4838-ba04-5163021d1a06}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"6.1.0\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"946ceb1b-07a1-49fc-960a-4a9317a84e44\",\"fxmonitor@mozilla.org\":\"8167defa-464d-4f60-89d4-a2bd75e768d9\",\"screenshots@mozilla.org\":\"1208728c-f384-46db-a6a5-c5a98e696b5e\",\"webcompat-reporter@mozilla.org\":\"a98da91b-d854-44f2-ab18-c3a3b49e6b09\",\"webcompat@mozilla.org\":\"5298febf-4103-4676-879a-d5fff8c8ea04\",\"default-theme@mozilla.org\":\"57d08f59-9a0a-47c9-87c8-59a00c41e087\",\"google@search.mozilla.org\":\"8cdf0689-9fe6-40f7-b98d-981a6a5e8900\",\"amazondotcom@search.mozilla.org\":\"b234f7dc-e5ea-4063-a29f-b5075d5eb910\",\"bing@search.mozilla.org\":\"c23369ea-79db-4cf2-a022-f50874cf1c26\",\"ddg@search.mozilla.org\":\"4008de7e-d6ba-4506-a5b2-805f9f33ca25\",\"ebay@search.mozilla.org\":\"728a4787-7fce-4abf-b965-b0a67526f7df\",\"twitter@search.mozilla.org\":\"cbb7035e-e673-40fa-9335-b075421ba315\",\"wikipedia@search.mozilla.org\":\"fb864ccf-5b4e-4ff6-81ca-dd9930ffd039\"}");
user_pref("idle.lastDailyNotification", 1572077844);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1572076245);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190718161435");
user_pref("media.gmp-manager.lastCheck", 1573212108);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1572077845);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "2155f8f3-8834-409b-8da1-6d610c3257c6");
user_pref("security.sandbox.plugin.tempDirSuffix", "00d88102-603d-4e4e-bd12-12237fa2e993");
user_pref("services.blocklist.pinning.checked", 1573212399);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1573172265255\"");
user_pref("services.settings.last_update_seconds", 1573212399);
user_pref("services.settings.main.cfr-fxa.last_check", 1573212399);
user_pref("services.settings.main.cfr.last_check", 1573212399);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1573212399);
user_pref("services.settings.main.hijack-blocklists.last_check", 1573212399);
user_pref("services.settings.main.language-dictionaries.last_check", 1573212399);
user_pref("services.settings.main.normandy-recipes.last_check", 1573212399);
user_pref("services.settings.main.sites-classification.last_check", 1573212399);
user_pref("services.settings.main.tippytop.last_check", 1573212399);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1573212399);
user_pref("services.settings.security.onecrl.checked", 1573212399);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1572077845);
user_pref("toolkit.startup.last_success", 1573212003);
user_pref("toolkit.telemetry.cachedClientID", "c9dff765-576e-47ad-87c2-ee9b73704d64");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
